/// <reference path="./custom-source.d.ts" />

const anime: Record<number, $app.AL_CompleteAnime> = {
  1: {
    id: 1,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Ariariana Man Succubus - Akuma Musume",
      romaji: "Ariariana Man Succubus - Akuma Musume",
      english: "Ariariana Man Succubus - Akuma Musume",
      native: "アリアリアナマンさっきゅばす ち〇ちん生えてる悪魔っ娘",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ234937_img_main%20(1).jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ234937_img_main%20(1).jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ234937_img_main%20(1).jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Majenta Rose",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  2: {
    id: 2,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Ore no Sefure wa Otokonoko",
      romaji: "Ore no Sefure wa Otokonoko",
      english: "Ore no Sefure wa Otokonoko",
      native: "俺のセフレは男の娘",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ099823_img_main.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ099823_img_main.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ099823_img_main.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Majenta Rose",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  3: {
    id: 3,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "SUCCUBUS T.G.D",
      romaji: "SUCCUBUS T.G.D",
      english: "SUCCUBUS T.G.D",
      native: "SUCCUBUS T.G.D",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ188959_img_main%20.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ188959_img_main%20.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ188959_img_main%20.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Majenta Rose",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  4: {
    id: 4,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Anomalous Coffee Machine",
      romaji: "Anomalous Coffee Machine",
      english: "Anomalous Coffee Machine",
      native: "Anomalous Coffee Machine",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/anomalous-coffee-machine-4270457604.png",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/anomalous-coffee-machine-4270457604.png",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/anomalous-coffee-machine-4270457604.png",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Horubrain",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  5: {
    id: 5,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Anomalous Coffee Machine II",
      romaji: "Anomalous Coffee Machine II",
      english: "Anomalous Coffee Machine II",
      native: "Anomalous Coffee Machine II",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/7TuVb7-742640027.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/7TuVb7-742640027.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/7TuVb7-742640027.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Horubrain",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  6: {
    id: 6,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 5,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Happy Island Fantasy",
      romaji: "Happy Island Fantasy",
      english: "Happy Island Fantasy",
      native: "Happy Island Fantasy",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/images%20(1).jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/images%20(1).jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/images%20(1).jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: HappyCreator",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  7: {
    id: 7,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 3,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Peeping Dorm Manager",
      romaji: "Peeping Dorm Manager",
      english: "Peeping Dorm Manager",
      native: "Peeping Dorm Manager",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/7310e27839bd5dff3563e7845bc4935beb8d_616xr353-948410900.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/7310e27839bd5dff3563e7845bc4935beb8d_616xr353-948410900.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/7310e27839bd5dff3563e7845bc4935beb8d_616xr353-948410900.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Horny Doge",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  8: {
    id: 8,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 7,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Summer Clover",
      romaji: "Summer Clover",
      english: "Summer Clover",
      native: "Summer Clover",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/download.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/download.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/download.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Connection",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  9: {
    id: 9,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "The Neighbor's Wife 2",
      romaji: "The Neighbor's Wife 2",
      english: "The Neighbor's Wife 2",
      native: "The Neighbor's Wife 2",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/5247020_ss-1.avif",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/5247020_ss-1.avif",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/5247020_ss-1.avif",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Aiban Works",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  10: {
    id: 10,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Winter - Life in the Countryside",
      romaji: "Winter - Life in the Countryside",
      english: "Winter - Life in the Countryside",
      native: "Winter - Life in the Countryside",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/4650718_1741441205301.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/4650718_1741441205301.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/4650718_1741441205301.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Dieselmine",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  11: {
    id: 11,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 4,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Natsu no Sagashimono",
      romaji: "Natsu no Sagashimono",
      english: "Natsu no Sagashimono",
      native: "なつのさがしもの",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/Natsu-no-Sagashimono-What-We-Found-That-Summer_BG_JP-2034537284.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/Natsu-no-Sagashimono-What-We-Found-That-Summer_BG_JP-2034537284.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/Natsu-no-Sagashimono-What-We-Found-That-Summer_BG_JP-2034537284.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Pekoge Studio",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  12: {
    id: 12,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    title: {
      userPreferred: "Kinjo no Hitozuma - Nakadashi Sex",
      romaji: "Kinjo no Hitozuma - Nakadashi Sex",
      english: "Kinjo no Hitozuma - Nakadashi Sex",
      native: "近所の人妻～中出しセックス",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ01078364_img_main.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ01078364_img_main.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ01078364_img_main.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Aiban Works",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  16: {
    id: 16,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    synonyms: ["Goodbye Eternity"],
    title: {
      userPreferred: "Goodbye Eternity",
      romaji: "Goodbye Eternity",
      english: null,
      native: "Goodbye Eternity",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/GE.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/GE.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/GE.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: RNGeusEX",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  17: {
    id: 17,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    synonyms: ["PUBPET", "PUPBET"],
    title: {
      userPreferred: "PUBPET",
      romaji: "PUBPET",
      english: null,
      native: "PUBPET",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/PUPBET.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/PUPBET.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/PUPBET.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Nekouji Studios",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  18: {
    id: 18,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    synonyms: ["Summer Life in the Countryside", "Summer - Life in the Countryside"],
    title: {
      userPreferred: "Summer Life in the Countryside",
      romaji: "Summer Life in the Countryside",
      english: null,
      native: "Summer Life in the Countryside",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ309178_img_main.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ309178_img_main.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ309178_img_main.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Dieselmine",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  19: {
    id: 19,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    synonyms: ["Ero Janken GHOST", "Erojanken GHOST hen"],
    title: {
      userPreferred: "エロじゃんけん GHOST編",
      romaji: "エロじゃんけん GHOST編",
      english: null,
      native: "エロじゃんけん GHOST編",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ01228955_img_smp2.jpg",
      large: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ01228955_img_smp2.jpg",
      medium: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ01228955_img_smp2.jpg",
      color: null,
    },
    bannerImage: null,
    description: "Publisher: Jermaneels",
    genres: [],
    averageScore: null,
    popularity: 0,
    startDate: { year: null, month: null, day: null },
    endDate: { year: null, month: null, day: null },
    relations: { edges: [] },
  } as unknown as $app.AL_CompleteAnime,
  20: {
    id: 20,
    idMal: null,
    format: "OVA",
    status: "FINISHED",
    season: null,
    seasonYear: null,
    episodes: 1,
    duration: null,
    countryOfOrigin: "JP",
    isAdult: true,
    synonyms: ["Ero Janken Kyonshi", "Erojanken Kyonshi hen"],
    title: {
      userPreferred: "エロじゃんけん キョンシー編",
      romaji: "エロじゃんけん キョンシー編",
      english: null,
      native: "エロじゃんけん キョンシー編",
    },
    coverImage: {
      extraLarge: "https://file.garden/al-ooJcQ9gJyjTQd/COVERS/RJ01479979_img_main.jpg
}

class Provider implements CustomSource {
  getSettings(): Settings {
    return { supportsAnime: true, supportsManga: false }
  }

  async getAnime(ids: number[]): Promise<$app.AL_BaseAnime[]> {
    const ret: $app.AL_BaseAnime[] = []
    for (const id of ids) {
      if (anime[id]) {
        const a = $clone(anime[id]) as any
        delete a["relations"]
        ret.push(a)
      }
    }
    return ret
  }

  async getAnimeDetails(): Promise<$app.AL_AnimeDetailsById_Media | null> {
    return null
  }

  // Generates one metadata entry per declared episode count, instead of
  // always returning a single "episode 1" entry regardless of actual count.
  async getAnimeMetadata(id: number): Promise<$app.Metadata_AnimeMetadata | null> {
    const entry = anime[id]
    if (!entry) return null

    const episodeCount = (entry as any).episodes ?? 1
    const episodes: Record<string, any> = {}

    for (let i = 1; i <= episodeCount; i++) {
      episodes[String(i)] = {
        episodeNumber: i,
        title: "OVA",
        image: null,
        length: null,
        summary: "",
        airDate: "",
      }
    }

    return { episodes } as unknown as $app.Metadata_AnimeMetadata
  }

  async getAnimeWithRelations(id: number): Promise<$app.AL_CompleteAnime> {
    if (anime[id]) return anime[id]
    throw new Error("not found.")
  }

  async getManga(): Promise<$app.AL_BaseManga[]> { return [] }
  async getMangaDetails(): Promise<$app.AL_MangaDetailsById_Media | null> { return null }

  async listAnime(): Promise<ListResponse<$app.AL_BaseAnime>> {
    return {
      media: Object.values(anime),
      total: Object.keys(anime).length,
      page: 1,
      totalPages: 1,
    }
  }

  async listManga(): Promise<ListResponse<$app.AL_BaseManga>> {
    return { media: [], total: 0, page: 1, totalPages: 1 }
  }
}
